apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-basic-credentials
  namespace: default
spec:
  encryptedData:
    password: AgAV7Z5bceJ1Kw7RU47WQ3OOGCyyB2gCGoZZz6OgN8Kl4MuFFz8CifnsMtiVwmjNoJ9pxjLcXqF75eqIvOlaCN+TxVljvhzgOC7CobtF5AsIICs3+pnNFmCuLgX2fE86NO1+ricqSFOr/xRd/Y6OCG4TYg6H/C8C3NeaErKJgoTm5IIR6E4NWFOt9QoDic5GonYbZIXj76y210wRwhcFLPEGh+KwBFFIybBpc8LmsiLNFhjcp31xgMrCK5+nriI5axlOL8nbd2oNPqnj+aRfCvdbbfy5oIsdKAVFbxARv9DkIgXbicLgU1jySMZJHtoDBHlgUESLPEVS5/oyqrj/mKkRpj3CtLAXRXzYVI0KqyBVL/M/BI6ZsXLzDIDHVuPq9/R3ccrd/1mEMCBm8Bxa8VnOUjzny6RWqksqoT7y0mBpB5PD4Yp0JKC3DDzO+eL4DIjwUTbWWd78Cl+nAU93/Wk79iPTTuXHwl70UHhD4DARUSCvKI3e57WDYbqvGbNT1Chvg3jYJ0aeHPVL0V2i9E5D3Mi4S9bDof+WKwRHQADLccsJR4f3/zYe499eJwdCGV5STF7zN62Rcyz2EwRe1byTzffTJC3BjdWGKJToAWe6tK2bi11Cph7aR/BQ1i2aWMNmt0VGCJ+ABqfUqihPnobTI8keyJyFfjBAaZIjgVEDLP8tA8omfVYeqNUJWHfhFxNfZ3I5OA==
    username: AgDOxAJTW4o3obtIXR1PgUyH0+0vLfW2LIGqjLpK/jzmoOwp0HdYnv4iyoOTEtvx/QTK5dREo+IK4+USX8+ZMVa6V90pDYp5Fk0SzRwvS6K2+0Szh0Pcew8k+J2vMZuvXXOELlX4ON2+J+blYVWkPdZFgfV+qLQsL7olBGWkt0iFnfIWOOJJpE9of9U+zyyEujT0I+P1qxakPiIjp1yt/KV/8RQdlrYSLzS2bo2DoyPtceBPPToF5K/8DWA1mPDh6p18M1SwmdJXlTu9NmkE6MvgPTn9iA3/+91lk2QBBsZqoMW1Cl6CPYpfrjMkMWXZ6AuCcN+yj3vgZj7FjQ+NKOCyueED2dRjSmNWJkeL3WKTRwFR1QOUtsBtDyEj6HaKHfOx3jh6Wp8FuVgAFLavEwxNmwkjgXW/Xf4A2nem+djJFBwkkLXt5EDIYTrLGbjTyF9F2j+/LFS1iQjQIAlQzPBSCreJfKJZ8ypN+euw6HkWZCJwngjOCqoUFdZT/X5/M8PV72sTwPQd194JYijXAzepKhj/AVfeTmBhvKtNNEFes0USZQxgAWWfFVEsDWcJx84vBMeLFYiwX2DNUXTQd9tGDu55H4rmyC85G3w3ve1NVZFvtqlWV3wzf8zoj9hbIPhaML55B8bOgpsorc0QSsWt2JHCiV+IrkTYRRcWJsQbfWRgXqo+2/orIg5XxCcBsQmFAxYmYw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: secret-basic-credentials
      namespace: default

