apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-bearer-credentials
  namespace: default
spec:
  encryptedData:
    token: AgCH3E5iQ9QeA9YqZkXT7ts/yIscPKJa+yNY9wRWVfJ0FiJFDEAelYPNwzLmNEjj6ZqXAjLOkjNFAifO08bHR20f/nk5hieuzlgzKJhFaikRGbMk3OOV8Bh+FLisforxwKTEwzNic4Svkm36GHsgjh6dToH8Ihl32rYG+kuhqH0l92YzJHjMilLfLqjKfY5tf8E1xN6evyer+GUGJPEAnIwxobBGV5Eduf4gFyVNJLuugi8Xml0OrrTGjp0rznzwhPIuVxcU+k/XpRQbPcL5U3rx+uBNpwFsJVafMhx1qw0Ydm/DKI6NR0T+3mjq+dFGu2Z5SUZSmTB0iNbZt/SvfHF/on+z4jZk92j083vtr3McA89ERAzApNiCIN4gHsVFs1KadcGLLB3plToTFiFbgaV9KuE+9HvqwD4OETcFGH/NZD7LOLloQk8coKDjJTSgfY8hnMBsE1kJyECwbKIBay6K8TSoVAdLSe+VjcDcpZS1vFtDphUsGjg7zJwFLrtUIhSMsbBJ7QA/NuYLpm6VRA2beeI/I/R0GmPh24nhtr8UDbo/AVyy7mHiJi4fdaiJ1VQIxSAxfQ3OHzvDXHgRIQOAwtBBOgtd8Z+fAot84nGwzoONfE/gZ+wb8F1lCijrlbD17eJhPmSGw4gxxs0HqBqcZk3J5Ct4WUmAMNK/Rnce9ZYLjTa/n+WJjHE6UpgFctzY30sQby88FTmAmDPX4YTnNiugugsROz8ainffDTTWQH5Vk5y2gZQ=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: secret-bearer-credentials
      namespace: default

