apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-bearer-credentials
  namespace: default
spec:
  encryptedData:
    token: AgA7WVl13b9mmuSzRjP9YzVW2Veu5gMesrq83wM8D882H1RgtBWUG3z5TYr0h+4VltFw/3RgY814X8v4tZ44GXBvdXVrnV7xeWzTiLiHo4wGhXRiYz6NZWVf2jidlmXsJOrH+9KThl3BHtQp8YyT/VyB5nNAImpL2dwwZtqWXyvPbzwMLg70Oy3S/AJEYU7hJ/S+E4LGywTZF5fgoF/m+qtNZTjDzEgmHGITu//XOYtpObTqmIHqNNFKqwBcMEhFM6TcMreGQNbKtgnzDQ01Rdap75NeE5nLDpWEXiZ2BRMwvD7Uwzlsl740p+zr9PgEhwT0bW6fZcqU0WnywIeDpSGtrqspz75SSXq14ALsXeLvNJT+nLwbNfgK+PGGrD5cqZIBXEylsXonRhlqkUGJ7cqpZLN1iugWkPot7BqdcMjJeY8yMFw9XoPV96lUpxeNU44CrQHG2sDdBtX9QwPTllqUzO+a2ZpWYl9G+QXK5UlfQj0J72dLV2cwvSe8GB+ugh6SIFZsurijvVt3pB6kkSkB2D9PpEbOW4nv0Ihd3sMCQP/nlhkvtwTgYmQFHAPFozSeSbKi0sk0CrgZQqs0iqZ3ZL9bXIftfyIwQUiZIYmPzYAfzGwyWW3dL8IlbOaVMhuhsNj/oY53Y7SjoPYaOM3UFinTbF+ujhl8FhI5Tlt0FOK47BROWcf/6MKWHP8gwnGKg1yygG2R8C5VVP7WcNMkN7ayO+bBM0xfU4s4x2r7TZRbc1f/ZWQ=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: secret-bearer-credentials
      namespace: default

